### ISSUE TITLE
How to Enable

### ISSUE THREAD

**Issue by Humorist2601** [indrastorms/Dropped-Patches#53]
Hello

I want to know how to enable these patches on the default Revanced Manager app as I want to use the Spotify Patch

**Comment by indrastorms** [comment]
Same as other bundles
![Screenshot_20240429-081749](https://github.com/indrastorms/Dropped-Patches/assets/48489074/f1353c0e-f504-42aa-9365-adb2c532070e)

**Comment by Humorist2601** [comment]
I don't know if I am missing a step or not but I did what you have shown in your screenshot but on the main screen the Revanced Patches just shows Loading indefinitely.

![Screenshot_20240502-022523](https://github.com/indrastorms/Dropped-Patches/assets/97790626/acc3adfa-89f0-4323-9fe5-84e636995cbe)

**Comment by Snuupy** [comment]
running into same issue, used to work, now patches don't load

**Comment by indrastorms** [comment]
Use revanced-cli. Manager has skill issue.

**Comment by indrastorms** [comment]
Try latest it should fix now

**Comment by Snuupy** [comment]
> Try latest it should fix now

yes it works now, fixed! ♥️

**Comment by indrastorms** [comment]
@Humorist2601 if it doesn't work please reopen the issue.
